import "./globals.css";
import { Open_Sans } from "next/font/google";
import Header from "./components/Headers/Header";
import Providers from "./Providers";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="flex flex-col min-h-screen transition duration-300 ">
        <Providers>
          <Header />
          <main className="grow w-full max-w-[1220px] mx-auto py-10 border">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
