import "./globals.css";
import { Open_Sans } from "next/font/google";
import Header from "./components/Headers/Header";
import ProviderAuth from "./context/AuthContext";
import Providers from "./context/ThemeContext";
import SWRProvider from "./context/SWRConText";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="flex flex-col min-h-screen transition duration-300 ">
        <ProviderAuth>
          <Providers>
            <Header />
            <main className="bg-primary grow w-full max-w-[1220px] mx-auto py-10 border">
              <SWRProvider>{children}</SWRProvider>
            </main>
          </Providers>
        </ProviderAuth>
      </body>
    </html>
  );
}
